# Generated by Django 5.1.5 on 2026-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('page_view', 'Vista de página'), ('busqueda', 'Búsqueda'), ('busqueda_sin_resultados', 'Búsqueda sin resultados'), ('agregar_carrito', 'Agregar al carrito'), ('checkout_iniciado', 'Checkout iniciado'), ('pedido_creado', 'Pedido creado')], db_index=True, max_length=30, verbose_name='Tipo de evento')),
                ('ruta', models.CharField(blank=True, max_length=255, verbose_name='Ruta')),
                ('producto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de producto')),
                ('termino_busqueda', models.CharField(blank=True, max_length=200, verbose_name='Término de búsqueda')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Evento de métrica',
                'verbose_name_plural': 'Eventos de métrica',
                'ordering': ['-created_at'],
            },
        ),
    ]
