# Generated by Django 5.1.5 on 2026-06-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('mercadopago', 'Mercado Pago')], default='whatsapp', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='MP Payment ID'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='MP Preference ID'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='MP Status'),
        ),
    ]
