# Generated by Django 5.1.5 on 2026-07-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['activo'], name='categoria_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='producto_activo_idx'),
        ),
    ]
