# Generated by Django 5.1.5 on 2026-07-28 13:13

import apps.productos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_descripcion_categoria_categoria_activo_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='productos/thumbs/', verbose_name='Miniatura (generada automáticamente)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Se redimensiona y convierte a WebP automáticamente al guardar.', null=True, upload_to='productos/', validators=[apps.productos.validators.validar_imagen_producto], verbose_name='Imagen'),
        ),
    ]
